Make changes for iteration 3 spec harness
lgsriclas/black_thursday pull request #10
Opened 2021-09-16 21:34 UTC by lgsriclas

2021-09-16 21:46 UTC, michab17 approved these changes

2021-09-16 22:13 UTC, samueldevine requested changes
very minor changes added - great refactor!

2021-09-16 22:13 UTC, samueldevine commented on lib/invoice_item_repository.rb
> +    rows = CSV.read(@path, headers: true, header_converters: :symbol)
we can update the `@path` to `path` here

2021-09-16 22:13 UTC, samueldevine commented on lib/invoice_item_repository.rb
>      result
no need for this result anymore :)

2021-09-17 15:30 UTC, samueldevine approved these changes

2021-09-17 15:30 UTC, samueldevine commented
looks good to me! ready to merge

2021-09-17 16:16 UTC, merged